name:                strong-vector
version:             0.1.0.0
github:              "samuelhklumpers/strong-vector"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/samuelhklumpers/strong-vector>

dependencies:
- base >= 4.7 && < 5
- constraints
- reflection
- distributive
- adjunctions
- comonad
- lens
- containers


ghc-options:
- -O0

default-extensions:
- DataKinds
- GADTs
- ScopedTypeVariables
- FlexibleInstances
- TypeOperators
- TypeApplications
- PolyKinds
- TypeFamilyDependencies
- RankNTypes
- MultiParamTypeClasses
- StandaloneDeriving
- BlockArguments
- ConstraintKinds
- FlexibleContexts
- LambdaCase
- EmptyCase

library:
  source-dirs:  src
  ghc-options:
  - -Wall

tests:
  strong-vector-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec  
    - hspec-contrib                   
    - HUnit  
    - QuickCheck                 
    - quickcheck-classes-base   
    - strong-vector
